### ISSUE TITLE
Attachment bigger then 3mb is broken

### ISSUE THREAD

**Issue by robayo** [Azure/Microsoft365R#192]
Hey all, 
I use this library daily and it has been working perfectly for sending emails with attachments bigger than 3mb but today it stoped working. Nothing has changed but R now throws this error:
`Error in make_large_attachment(object, self) : Unauthorized (HTTP 401).`

When debugging the URL that is sent I get this error:
`{"error":{"code":"InvalidAudienceForResource","message":"The audience claim value is invalid for current resource. Audience claim is 'https://outlook.office.com/api/', request url is 'https://outlook.office365.com' and resource type is 'Exchange'.","innerError":{"oAuthEventOperationId":"f6eb9336-3285-4258-b8ed-fa195ff2fbdd","oAuthEventcV":"E2tF021AVOB25M0eERD1Pw.1.1","errorUrl":"https://aka.ms/autherrors#error-InvalidResource","requestId":"d3456b13-406d-e054-76e4-cd1e1110f53f","date":"2023-11-29T22:26:42"}}}`

 I don't know if the API is now fully deprecated for Outlook. Is there a timeline for migrating fully to the Graph API in Outlook?

**Comment by apalacio9502** [comment]
Hello,

The same thing is happening to us. I have been reviewing, and I think it would be interesting to consider migrating everything to the Graph API because the method currently being used is already deprecated. However, I believe that will take some time, and **I'm not sure if there is a temporary solution to this issue.**

Regards,

**Comment by apalacio9502** [comment]
Hello,

I think the error is related to the fact that the dev version does not support "Create session to attach large file", however, reading the AzureGraph API Beta documentation it does not say that files larger than 3 megabytes cannot be sent by "Add attachment to a message", I tested and was able to send 20 Mb without problem.

I think it would be important to validate what step to follow with the attachments because reading the documentation the "Create session to attach large file" is already deprecated and will be eliminated at the beginning of next year

Regards,

**Comment by hongooi73** [comment]
Microsoft365R doesn't use the old Outlook API at all, it's purely Graph. This might just be a glitch on the MS side. If possible, wait a day or two and try again.

**Comment by hongooi73** [comment]
@apalacio9502 I don't see any indication that it's deprecated. Is this what you're looking at?

https://learn.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-beta&tabs=http

**Comment by apalacio9502** [comment]
> Microsoft365R doesn't use the old Outlook API at all, it's purely Graph. This might just be a glitch on the MS side. If possible, wait a day or two and try again.

I thought it was a glitch on the MS side, however I tested using the same user in python with the library https://github.com/vgrem/Office365-REST-Python-Client, and it did not generate an error, reading the documentation I understand that it uses the same technology.

On the other hand, I am sure that it is not a problem related to the libraries called by Microsoft365, since I carried out tests in an environment in which the R libraries have not been updated since June and until Monday the sending of emails with attachments worked correctly.

**Comment by apalacio9502** [comment]
Debugging the function, I see the same error that happens to @robayo 

`{\"error\":{\"code\":\"InvalidAudienceForResource\",\"message\":\"The audience claim value is invalid for current resource. Audience claim is 'https://outlook.office.com/api/', request url is 'https://outlook.office365.com' and resource type is 'Exchange'.\",\"innerError\":{ \"oAuthEventOperationId\":\"0434247c-8b96-4129-bf90-21b826a8efdc\",\"oAuthEventcV\":\"i0Ei/IV5FGlUavv756n8TA.1.1\",\"errorUrl\":\"https://aka. ms/autherrors#error-InvalidResource\",\"requestId\":\"fc22418b-7985-6914-546a-fbfbe7a9fc4c\",\"date\":\"2023-12-01T04:51:20\"} }}`

**Comment by hongooi73** [comment]
The R code only uses the Graph API, including any attachment-related calls. However, under the hood the Graph API might call the Outlook API, which is what causes this error.

So, it looks like there's a new tasks API that replaces Outlook. I'll see what I can do.

**Comment by robayo** [comment]
The problem seems fixed by Microsoft for now. Nevertheless I hope that on March 2024, when the Outlook API is fully deprecated, the returned uploadUrl is changed to a Graph API endpoint automatically. We have to keep checking that.

**Comment by hongooi73** [comment]
I think this was just a momentary glitch in the matrix.

There's no indication that the Graph API endpoint to create large attachments is deprecated. The fact that the returned uploadUrl points to "outlook.office.com" shouldn't matter, since it isn't a user-visible URL: it's all handled by the code. Regardless, I've asked for clarification on this.

**Comment by hongooi73** [comment]
Closing as this appears to have been a temporary backend thing
