### ISSUE TITLE
Authenticate and access sharepoint in source code of Shiny app

### ISSUE THREAD

**Issue by agerns** [Azure/Microsoft365R#83]
Thanks Hong for writing [the vignette](https://github.com/Azure/Microsoft365R/blob/shiny-auth/vignettes/shiny.Rmd) and showing the basic template of how interactive authentication is possible in Shiny. 
This works perfectly! 

I now would like to authenticate and access sharepoint in the source-code of shiny, that is, outside the server/ui script but in the prior source script, so basically non-interactively. This is necessary as I have most of my code running in that space and require access to a sharepoint file previous to running most of my app. 

What would be the best approach here? Could I just run ```get_azure_token``` using ```auth_type="client_credentials"```, and then just run ```ms_graph$new(token=token)$get_sharepoint_site()```? All this being outside the shiny server? 
This doesn't seem to quite work, what am I missing? 

Thanks as always for any guidance here!

**Comment by hongooi73** [comment]
1. I'm not a Shiny expert, so I don't know if there's a special meaning to the term "source code" in that context. As far as I'm concerned, source code is the sum total of the R code that you pass to the Shiny server: ui, server, and anything else that gets used.

2. Your use case doesn't make sense. Do you mean that you need to access a file from Sharepoint before presenting a dashboard to the user? If so, how are you going to handle authentication?

3. The client credentials flow is almost certainly not what you want.

4. Regardless, this isn't the place to debug random user code. Since Microsoft365R now seems to be working satisfactorily with Shiny, I'm closing this. My advice is: rethink your app flow so that you do authentication _first_, get the file you need, and only then handle all the interactive dashboard bits. If you're really stuck and need help, send me an email with a detailed description of your workflow ideally including code.
